[build]
  command = "npm run build"
  publish = "frontend/.next"  # Use the correct build output directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
