[build]
  base = "frontend"          # Tells Netlify to run commands in /frontend
  command = "npm run build"
  publish = ".next"          # Because build output is at frontend/.next

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"